#Scott Wolfe
#CS2750 PA 6
#Date 11/17/2018

output: bank

bank: main.c deposit.c withdrawal.c
	gcc -o bank main.c deposit.c withdrawal.c add_account.c	remove_account.c balance_inquiry.c view_accounts.c


