#!/bin/bash

if [ $# -eq 0 ]
then
	counter=20
else
	counter=$1
fi

for i in $(seq 1 $counter)
do 
	if !(( $i % 3 )) && !(( $i % 5))
	then
		echo "FizzBuzz"
	elif !(( $i%3 ))
	then 
		echo "Fizz"
	elif !(($i%5))
	then 
		echo "Buzz"
	else
		echo "$i"	
	fi
done
