#Scott Wolfe
#CS2750 PA 5
#Date 11/1/2018

output: deater phone

deater: main.c sum.c scarecrow.c
	gcc -o deater main.c sum.c scarecrow.c

phone: phone.c phone_fmt.c
	gcc -o phone phone.c phone_fmt.c


